package com.gahov.prweather.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * An entity representing weather data, typically stored in a database.
 *
 * @property id The unique identifier for the weather data entry.
 * @property cityName The name of the city associated with the weather data.
 * @property countryName The name of the country associated with the city.
 * @property weatherDescription A description of the weather conditions.
 * @property temperatureKelvin The temperature in Kelvin units.
 * @property humidity The humidity level.
 * @property windSpeed The wind speed.
 * @property iconId The identifier for the weather icon.
 * @property time The time associated with the weather data.
 */


@Entity(
    tableName = "weatherData"
)
data class WeatherDTO(
    var id: Long? = 0,
    var cityName: String? = "",
    var countryName: String? = "",
    var weatherDescription: String? = "",
    var temperatureKelvin: Double? = 0.0,
    var humidity: Int? = 0,
    var windSpeed: Double? = 0.0,
    var iconId: String? = "",
    var time: String? = ""
) {

    /**
     * The primary key auto-generated by the database.
     * That means that the DTO is not unique.
     */

    @PrimaryKey(autoGenerate = true)
    var uid: Long = 0
}